### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by chatchoi** [NICUP14/MiniLang#4]
I know about your language from lobste.rs, but I can't comment because I don't have an account. You should have a look at @IsaacShelton's Adept language. It's very similar to yours. You guys have a very similar avatar, too.

**Comment by NICUP14** [comment]
I'm really impressed by Isaac's commitment to the project. His programming language is far more mature than `MiniLang`. I do see some resemblance between the two syntactically and structurally, even tho the design goals seem to be different. It would be interesting to hear the author explain his design goals and motivation for the language. It doesn't appear in the documentation

**Comment by chatchoi** [comment]
You can reach out to him in:

https://github.com/AdeptLanguage/Adept/issues

He is more active in https://github.com/IsaacShelton/Adept3x/issues, though.
